version: "3.9"

services:
  nodejs-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3080:3080"
    container_name: node-api
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
  vue-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8061:8080"
    container_name: vue-ui
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules